version: '3.9'

services:
  forditasokkapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:44330
      - ASPNETCORE__Kestrel__Certificates__Default__Password=forditasokkPwd
      - ASPNETCORE__Kestrel__Certificates__Default__Path=/https/authServer.pfx
    ports:
      - "44330:44330"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https:ro
  auth_server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:44338
      - ASPNETCORE__Kestrel__Certificates__Default__Password=forditasokkPwd
      - ASPNETCORE__Kestrel__Certificates__Default__Path=/https/authServer.pfx
    ports:
      - "44338:44338"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https:ro
  db:
    image: postgres
    restart: always
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres